createDeployment: true

replicaCount: 1

containerPort: true

container:
  image:
    repository: myapp
    pullPolicy: IfNotPresent
    tag: ""
  port: 9000

service:
  type: ClusterIP
  port: 9000

resources: {}